### PR TITLE
Add Travis CI config

### PR DESCRIPTION
**Pull request by ddbeck**
(This supersedes #25.)

This is a first step to resolving #21 and shipping a package.

This PR adds a Travis CI file that builds the package, runs the tests, and then verifies that the package can be installed (as we talked about on #17). It will also publish tags to npm (à la browser-compat-data).

~This is in draft status to test whether it works. It still needs docs.~

### CODE REVIEW

**Comment by ddbeck** [comment]
@wbamberg OK, this PR should behave properly now. As you can see, we now have builds (e.g. the results of "Show all checks") on a real PR. 🎉

The only remaining configuration is to get an npm token for the https://www.npmjs.com/~mdn account and add it to the Travis CI build settings as `NPM_TOKEN`. Any idea who has credentials for that?

Otherwise, I think this is ready for your review. Thank you!

**Comment by wbamberg** [comment]
> The only remaining configuration is to get an npm token for the https://www.npmjs.com/~mdn account and add it to the Travis CI build settings as NPM_TOKEN. Any idea who has credentials for that?

@chrisdavidmills , @Elchi3 , do you know the answer to this?

**Comment by Elchi3** [comment]
I've added a new NPM_TOKEN to the mdn/short-descriptions travis config.

**Comment by ddbeck** [comment]
@Elchi3 thank you!

@wbamberg that's everything then. I think this is ready for your review.

**Review by wbamberg — APPROVED** [review]
I'm not at all familiar with this but it look plausible. Let's see if it works :)

**Pull request merged**
